//COIN AUCTION ACTION TYPES

export const UPDATE_UPCOMING_AUCTIONS = 'UPDATE_UPCOMING_AUCTIONS';
export const UPDATE_ARCHIVE_AUCTIONS = 'UPDATE_ARCHIVE_AUCTIONS';
export const UPDATE_LANDING_COINS = 'UPDATE_LANDING_COINS';
export const UPDATE_BUYING_COINS = 'UPDATE_BUYING_COINS';



//SELLING COIN ACTION TYPES
export const FETCH_SELLING_COINS = 'FETCH_SELLING_COINS';
export const FETCH_SELLING_COIN_DESC = 'FETCH_SELLING_COIN_DESC';

//CART ACTION TYPES
export const ADD_COIN_TO_CART = 'ADD_COIN_TO_CART';
export const UPDATE_CART_FROM_COOKIE = 'UPDATE_CART_FROM_COOKIE';
export const UPDATE_COIN_QTY = 'UPDATE_COIN_QTY';
export const REMOVE_COIN_FROM_CART = 'REMOVE_COIN_FROM_CART';
export const ADD_QUANTITY = 'ADD_QUANTITY';
export const SUB_QUANTITY = 'SUB_QUANTITY';
export const CLEAR_CART = 'CLEAR_CART';


//USER ACTIONS TYPES
export const FETCH_USER_DETAILS = 'FETCH_USER_DETAILS';
export const UPDATE_USER_DETAILS_FROM_LOGIN = 'UPDATE_USER_DETAILS_FROM_LOGIN';
export const UPDATE_USER_DETAILS_FROM_COOKIE = 'UPDATE_USER_DETAILS_FROM_COOKIE';
export const USER_LOGOUT = 'USER_LOGOUT';
export const UPDATE_USER_PROFILE_DETAILS = 'UPDATE_USER_PROFILE_DETAILS';

//LOGIN MODAL TYPES
export const OPEN_LOGIN_MODAL = 'OPEN_LOGIN_MODAL';
export const CLOSE_LOGIN_MODAL = 'CLOSE_LOGIN_MODAL';

//BID MODAL TYPES
export const OPEN_BID_MODAL = 'OPEN_BID_MODAL';
export const CLOSE_BID_MODAL = 'CLOSE_BID_MODAL';